
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mahwbmitxkrxpfobnfai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1haHdibWl0eGtyeHBmb2JuZmFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDAzMDEsImV4cCI6MjA1ODAxNjMwMX0.U0TVqTbk3gd-5K7SfKsb_ALYpcI6N7usO4jWTxymi8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
